### ISSUE TITLE
Style element error

### ISSUE THREAD

**Issue by dontwork** [jfgodoy/vite-plugin-solid-svg#13]
Im not sure what the cause is, but when i try to use this plugin with an svg with a style block in it, it errors like so:

```
Unexpected token, expected "}" (1:255)
```

The character it is referring to is the first colon from the style block

**Comment by jfgodoy** [comment]
hi @dontwork, thank you for the report. 
The classes definition inside style block, for example `.foo{opacity:0.5}` were been interpreted for solid. I just fixed it scaping the curly brackets.
I published the fix as 0.3.1
