### ISSUE TITLE
SVGO config isn't working when importing as component

### ISSUE THREAD

**Issue by MrFoxPro** [jfgodoy/vite-plugin-solid-svg#15]
Try to create `svg.config.js` in project root: 
```js
module.exports = {
   multipass: true, // boolean. false by default
   datauri: 'enc', // 'base64' (default), 'enc' or 'unenc'.
   js2svg: {
      indent: 2, // string with spaces or number of spaces. 4 by default
      pretty: true, // boolean, false by default
   },
   plugins: [
      // set of built-in plugins enabled by default
      'preset-default',

      // enable built-in plugins by name
      'prefixIds',

      // or by expanded notation which allows to configure plugin
      {
         name: 'sortAttrs',
         params: {
            xmlnsOrder: 'alphabetical',
         },
      },
   ],
}
```
You will see errors: 
![image](https://user-images.githubusercontent.com/17229619/182376583-391a1463-30e8-4f6b-af3b-11b3f849c657.png)

**Comment by MrFoxPro** [comment]
The problem is with `datauri` field.

**Comment by jfgodoy** [comment]
hi @MrFoxPro, this plugin works returning a solid component as `export default (props) => <svg {...props}>...</svg>`. The svg part is the result of svgo, so it's required that the result be an unencoded svg. You can fix it for now removing the `datauri` property or assigning a falsy value. 

I will add a check of the datauri property before closing this issue
