### ISSUE TITLE
Pass props.children

### ISSUE THREAD

**Issue by MrFoxPro** [jfgodoy/vite-plugin-solid-svg#18]
I want to add some elements inside svg. For example:
```tsx
<Icon
   classList={{
      active: editor.tool === type,
   }}
   onClick={[onClick, type]}
   children={<title>I'm a circle</title>}
  >
<title>{t().icon_title}</title>
</Icon>
```
How is it possible to achieve this?

**Comment by jfgodoy** [comment]
hi @MrFoxPro. This use case isn't currently supported.

When the component is compiled, the first step is to replace the original svg source with `source.replace(/([{}])/g, "{'$1'}")` to avoid any value inside `{ ...}` being  interpreted as a Solid.js accesor. This is why we can't use `{props.children}` inside svg. I had  to do  the replacement to avoid styles interpreted as Solid.js accesors. Check out this example:
```
<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20">
  <style type="text/css">
    .dot{opacity:0.5}
  </style>

  <circle cx="7" cy="7" r="5" class="dot" fill="red"/>
  <circle cx="12" cy="12" r="5" class="dot" fill="yellow"/>
</svg>
```

I will add an exception just for "{props.children}"

**Comment by jfgodoy** [comment]
checkout the pull request #19 and let me know if it works for you
