### ISSUE TITLE
Add option to use TypeScript defenisions with defaultAsComponent: true

### ISSUE THREAD

**Issue by nirtamir2** [jfgodoy/vite-plugin-solid-svg#24]
Hi
I use this library and it works great!
I notice that when I use

```ts
 solidSvg({
        defaultAsComponent: true
      }),
```

option, the TypeScript definitions won't work (because they are not cover .svg without `?component-solid`)
Can you provide another duplication type definitions that can be consumed if we use this `defaultAsComponent`?
Or I should just declare them myself?

Currently I added `solid-svg.d.ts` in my project with
```ts
declare module "*.svg" {
  import type { Component, ComponentProps } from "solid-js";
  const c: Component<ComponentProps<"svg">>;
  export default c;
}

```

Thanks!

**Comment by MrFoxPro** [comment]
@nirtamir2 Did you add `vite/client` types to tsconfig / .d.ts entry as pointed here https://vitejs.dev/guide/features.html#client-types?

**Comment by MrFoxPro** [comment]
Basically yes.. In case with defaultAsComponent you need to add ambient defenition in project

**Comment by nirtamir2** [comment]
Yes, this is what I've done.
I can keep my solution. 
But not sure if it's better to keep it that way or export the types from the library.
I can close this issue if you think it's better that the user will define its own TypeScript declarations for SVG in this mode

**Comment by nirtamir2** [comment]
BTW - I think it's better to also document it in the README that we can still import svg as URL for `img` tag with:
```
import SolidIconSrc from "~/assets/solid.svg?url";

 <img src={SolidIconSrc} alt="solid icon" height={24} width={24} />

```

**Comment by nirtamir2** [comment]
Looks great!

**Comment by jfgodoy** [comment]
hi @nirtamir2 and @MrFoxPro! I'm agree with adding a second `.d.ts` file.
The `vite-plugin-solid-svg/types-default` must be included before `vite/client` to take effect.

**Comment by ivancuric** [comment]
Bumping this old thread - seems that the `vite-plugin-solid-svg/types-default` doesn't work even when used as
```
"types": ["vite-plugin-solid-svg/types-component-solid", "vite/client"],
```
It's just being interpreted as a string.
![image](https://github.com/jfgodoy/vite-plugin-solid-svg/assets/2827047/e5e09858-36d6-4c72-a9c3-8075d220b6e3)

I'm using ` "vite": "^4.4.2",` and ` "typescript": "^5.1.6",`

**Comment by MrFoxPro** [comment]
@ivancuric check out this:
```
// tsconfig.json
"compilerOptions": {
  "types": [
    "vite-plugin-solid-svg/types-component-solid"
    "vite/client",
  ],
},
```

**Comment by MrFoxPro** [comment]
#31

**Comment by MrFoxPro** [comment]
Hm I checked now and seems like that way doesn't work if you will build from node_modules
So another way is to clone my branch, run `pnpm i && pnpm build` and then isntall it in your project via `pnpm i <path/to-repo>`

**Comment by jfgodoy** [comment]
hi @ivancuric!, Do you still have the issue? I can't reproduce it.
@MrFoxPro thank you very much for the support. The PR seems to be ok, I will merge it and publish.

**Comment by ivancuric** [comment]
Hey, haven't had the time to check out the branch.
