### ISSUE TITLE
this plugin doesn't work with solid-start/vite

### ISSUE THREAD

**Issue by joshbedo** [jfgodoy/vite-plugin-solid-svg#27]
this was working fine with `vite-plugin-solid` but doesn't seem to be working with `solid-start/vite`. The imports don't work and you get a Comp is not a function error. Feel like this is important since Solid Start is basically the create-next-app for SolidJS.

**Comment by jfgodoy** [comment]
hi @joshbedo thank you very much for the report, and sorry for my delay. I haven't been able to reproduce the error, so for now, I will close this issue.
