### ISSUE TITLE
Resize issue

### ISSUE THREAD

**Issue by asgharh24** [jfgodoy/vite-plugin-solid-svg#29]
Sorry maybe I'm just doing something stupid but I cant seem to resize the SVG by using the width attribute, inline style for width or tailwind. Setting these attributes just crops the svg. Am I missing something or does this plugin not support resizing?
Using transform/scale distorts the SVG and it continues taking up space of the original svg.

**Comment by asgharh24** [comment]
The svg gets rendered without the viewBox attribute. I can get it resize properly by setting the viewBox attribute.

**Comment by maxjvh** [comment]
ran into the same issue, just disable svgo via the options to keep the viewbox attributes

**Comment by jfgodoy** [comment]
hi @asgharh24, sorry for the late response. All the props are passed to the SVG element, but `svgo` removes the viewBox property  by default (using the built-in plugin removeViewBox [see more](https://github.com/svg/svgo#built-in-plugins)).  You have two options: you can disable `svgo` as @maxjvh suggested, or you can configure it to only disable that specific plugin.
