### ISSUE TITLE
How to Forward props to SVG Element  change storeke color 

### ISSUE THREAD

**Issue by army-u8** [jfgodoy/vite-plugin-solid-svg#32]
In my project, a svg icon uses different colors in different places. I hope to change the color dynamically by passing parameters. Can you give me an example? Thank you

**Comment by MrFoxPro** [comment]
@army-u8 you can pass `fill="red"` or `stroke="blue"` attributes to component
Or, yo can use `class="<class>"` and then reference it in selectors. It's even possible with atomic CSS like UnoCSS or tailwind.

**Comment by MrFoxPro** [comment]
@army-u8 I checked and seems like there is issue with svgo
Try it with 
```
svgo: {
   enabled: false,
},
```

**Comment by army-u8** [comment]
![image](https://github.com/jfgodoy/vite-plugin-solid-svg/assets/106830983/34afbb56-19eb-44ca-9a97-92025804ca98)
 
@MrFoxPro What I want to change is the stoke attribute of each path. Is it possible?

**Comment by MrFoxPro** [comment]
If you're using tailwind/unocss, you can use `[&>path]:stroke-red` with arbitrary variants

With plain css, you can add `class="your-class"` and then in your CSS:
```css
.your-class path {
  stroke: red;
}
```

**Comment by army-u8** [comment]
> If you're using tailwind/unocss, you can use `[&>path]:stroke-red` with arbitrary variants
> 
> With plain css, you can add `class="your-class"` and then in your CSS:
> 
> ```css
> .your-class path {
>   stroke: red;
> }
> ```

 It worked, thank you for helping me to solve this problem
