### ISSUE TITLE
Issues when defining extending environment variable types

### ISSUE THREAD

**Issue by gBasil** [jfgodoy/vite-plugin-solid-svg#33]
I believe #27 may be addressing the same issue. I have a project that uses SolidStart, and the types for `.svg`s don't seem to be working properly.

![image](https://github.com/jfgodoy/vite-plugin-solid-svg/assets/57513430/acba61f2-ae77-4b42-b252-5a2477902d75)

My `tsconfig.json`:
```json
{
	"compilerOptions": {
		"allowSyntheticDefaultImports": true,
		"esModuleInterop": true,
		"target": "ESNext",
		"module": "ESNext",
		"moduleResolution": "node",
		"jsxImportSource": "solid-js",
		"jsx": "preserve",
		"strict": true,
		"types": [
			"vite-plugin-solid-svg/types-component-solid",
			"solid-start/env"
		],
		"resolveJsonModule": true,
		"baseUrl": "./",
		"paths": {
			"~/*": ["./src/*"]
		}
	}
}
```

**Comment by jfgodoy** [comment]
Hi @gBasil! I can't reproduce the issue. I started from a bare solid start project and it works fine.
![image](https://github.com/jfgodoy/vite-plugin-solid-svg/assets/731635/82d4d6b6-1b52-4c5e-b643-4ab505be932b)

**Comment by jfgodoy** [comment]
Oh, right! I can reproduce it now. It seems that env.d.ts is being loaded before the types defined in tsconfig.json. To ensure that the types in vite-plugin-solid-svg/types-component-solid are loaded before vite/client, you can try the following:

```
/// <reference types="vite-plugin-solid-svg/types-component-solid" />
/// <reference types="vite/client" />

interface ImportMetaEnv {
	readonly VITE_SOME_ENV: string
}

interface ImportMeta {
	readonly env: ImportMetaEnv
}

export {};
```
