### ISSUE TITLE
"readFile" is not exported by "__vite-browser-external"

### ISSUE THREAD

**Issue by Kikketer** [jfgodoy/vite-plugin-solid-svg#37]
I'm able to run and see SVGs during development, however when I attempt to build I get the following error:
```
"readFile" is not exported by "__vite-browser-external", imported by "node_modules/vite-plugin-solid-svg/dist/es/index.mjs".
```

```
1: import { readFile } from 'node:fs/promises';
            ^
2: import { loadConfig, optimize } from 'svgo';
error during build:
RollupError: "readFile" is not exported by "__vite-browser-external"
```

I've been able to repeat this issue with a bare-minimum code sandbox: https://codesandbox.io/p/sandbox/vite-solid-svgs-m5mvzw?file=%2Fsrc%2FApp.tsx%3A7%2C19

You will see the SVG rendered properly but if you attempt to run `yarn build` it will throw the error.

**Comment by MrFoxPro** [comment]
@Kikketer This plugin reads SVG source to transform it to JSX. I was wondering myself how this should be done correctly. I tried via `this.load()`, but with no success.

**Comment by Kikketer** [comment]
Seems like a pretty critical bug figuring you can’t build the application.

**Comment by MrFoxPro** [comment]
> Seems like a pretty critical bug figuring you can’t build the application.

It should work locally
As of your error, seems like node dependencies are externalized in your environment

**Comment by Kikketer** [comment]
Building locally doesn't work either, the codesandbox was just an example of repeating the issue.
Is there a solution to this?  I'm not sure what you mean by "externalized in your environment"

**Comment by MrFoxPro** [comment]
> Building locally doesn't work either, the codesandbox was just an example of repeating the issue. Is there a solution to this? I'm not sure what you mean by "externalized in your environment"

I looked up your example and you're trying to use plugin in runtime/browser for some reason
![image](https://github.com/jfgodoy/vite-plugin-solid-svg/assets/17229619/4edd5913-1cfd-4fae-8ce6-4218686e2f39)
This is incorrect usage, it should only be uses in vite.config.ts in `plugins` sections. As I said, this plugin depends on node `fs` module.

**Comment by Kikketer** [comment]
Seems to me a bit of documentation update is needed. I'm not sure where I would have put the SolidSvg configuration.
I've since dropped this library, simply made my SVGs into TS files, then dropped SolidJS and moved on to using a new tech stack.

Thanks
