### ISSUE TITLE
Updating to 0.8.0 breaks Vite Typescript config imports

### ISSUE THREAD

**Issue by SomeAspy** [jfgodoy/vite-plugin-solid-svg#45]
![image](https://github.com/jfgodoy/vite-plugin-solid-svg/assets/33640860/d5c5fbc5-417a-4829-8da3-ec0a6d0f5296)

SVGs still load, and Vite building is still successful. This appears to be specifically an issue with the types if I had to guess.

**Comment by jfgodoy** [comment]
hi @SomeAspy 
which moduleResolution are you using in your tsconfig?. Should be different from node/node10.

**Comment by SomeAspy** [comment]
Ah yeah, I totally missed that was a long-deprecated option. I've updated it accordingly (to `NodeNext`)
However, after doing so, it still appears that `solidSvg()` is incorrectly typed.
![image](https://github.com/jfgodoy/vite-plugin-solid-svg/assets/33640860/1a73f22e-c8fa-457c-9ba2-054f3aa797d1)

I've attached my `tsconfig.json` in case this is another case of me messing up my configs.
```json
{
  "include": [
    "**/*.tsx",
    "**/*.ts",
    "vite.config.ts"
  ],
  "compilerOptions": {
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "alwaysStrict": true,
    "exactOptionalPropertyTypes": true,
    "noImplicitAny": true,
    "noImplicitOverride": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noPropertyAccessFromIndexSignature": false,
    "noUncheckedIndexedAccess": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "strict": true,
    "useUnknownInCatchVariables": true,
    "target": "ESNext",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "jsx": "preserve",
    "jsxImportSource": "solid-js",
    "types": [
      "vite-plugin-solid-svg/types-component-solid",
      "vite/client"
    ],
    "removeComments": true,
    "noEmit": true,
    "isolatedModules": true,
    "lib": [
      "DOM",
      "ESNext"
    ],
  }
}
```

**Comment by jfgodoy** [comment]
I checked out your repository, and it seems the issue is related to `vite-plugin-webfont-dl`. When I removed it from the plugin list, the error disappeared.
 It seems that `vite-plugin-webfont-dl` is unable to resolve Vite 5 when the `moduleResolution` is set to `NodeNext`. You can switch to using the `moduleResolution` "Bundler," which is the default configuration when using the Solid.js ts template.

**Comment by SomeAspy** [comment]
Oh I see, I could have sworn I tested it without `vite-plugin-webfont-dl` in the above image. Upon actually investigating, my VSCode will not update intellisense properly when the `tsconfig.json` is changed without reloading. Sorry!
