### ISSUE TITLE
<symbol> causes an import error?

### ISSUE THREAD

**Issue by vallafederico** [jfgodoy/vite-plugin-solid-svg#51]
Was trying to make an svg sprite work, and encountered some behaviour I can't explain. Not sure if it's a bug or I'm missing something, if it's the latter I apologise in advance, but:

This works

```html
<svg fill="none" viewBox="0 0 399 398">
  <symbol id="circle"></symbol>
    <circle cx="50" cy="50" r="50" fill="white" />
</svg>
```

This doesn't

```html
<svg fill="none" viewBox="0 0 399 398">
  <symbol id="circle">
    <circle cx="50" cy="50" r="50" fill="white" />
  </symbol>
</svg>
```

And throws the following error

```
code: 'BABEL_PARSE_ERROR',
    reasonCode: 'UnexpectedToken',
    loc: Position { line: 1, column: 70, index: 70 },
    pos: 70,
    syntaxPlugin: undefined,
    plugin: 'solid-svg',
    id: '{...}/socialSprite.svg?component-solid',
    pluginCode: 'export default (props = {}) => <svg fill="none" viewBox="0 0 399 398"/{...props}>',
    frame: '1  |  export default (props = {}) => <svg fill="none" viewBox="0 0 399 398"/{...props}>\n' +
      '   |                                                                        ^'
  },
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: undefined,
  data: undefined
}
```

Am I missing something? 
Is this expected? If so, is there a way to make this work?

Here's a link to [stackblitz](https://stackblitz.com/edit/solidjs-templates-3petcj?file=src%2Frandom.svg) relevant file is random.svg.

Thanks!

**Comment by jfgodoy** [comment]
Hi @vallafederico!
Thank you for the report and the demo.
This also works:
```
<svg fill="none" viewBox="0 0 399 398">
  <symbol id="circle">
    <circle cx="50" cy="50" r="50" fill="white" />
  </symbol>
   <use href="#circle" x="100" y="100" />
</svg>
```
It seems to be an optimization by SVGO. I tried disabling all SVGO optimizations, and it also worked. You can configure SVGO to disable the rule that is affecting this.

**Comment by jfgodoy** [comment]
disabling svgo `removeUselessDefs` fix the problem. You can configure svgo in its own file, or as solidSvg params:
```
solidSvg({
      svgo: {
        enabled: false,
        svgoConfig: {
          plugins: [
            {
              name: 'preset-default',
              params: {
                overrides: {
                  removeUselessDefs: false,
                },
              },
            },
          ],
        },
      },
    }),
   ```

**Comment by vallafederico** [comment]
Thanks for your patience, this makes a lot of sense now.
And thanks for the amazing work on this!
