### ISSUE TITLE
Support for SSR

### ISSUE THREAD

**Issue by leapofazzam123** [jfgodoy/vite-plugin-solid-svg#6]
Hi, I'n using this plugin on Solid Start SSR and got this error
![Screenshot_20211130-112624](https://user-images.githubusercontent.com/76893443/144001339-c4581609-d4a6-4ebc-8380-05725feb5f6b.png)
And looks like it's hardcoded for client-side rendering and not for server-side rendering. Can you make it not hardcoded and/or make it compatible with both CSR and SSR?

**Comment by jfgodoy** [comment]
hi @leapofazzam123, I just fixed in 0de97618b30819f72e2ca5e9be127a69a823ca5a.
could you check the main branch and see if it works for you?

**Comment by jfgodoy** [comment]
I've just published a new version that includes the fix. I will close the issue for now. Feel free to reopen it if you find some issue.
