### ISSUE TITLE
Error on build after update version 0.2.0

### ISSUE THREAD

**Issue by lucasdu4rte** [jfgodoy/vite-plugin-solid-svg#7]
Hi, needed an update to version 0.2.0, because of SSR support. But build returns this error:

```shell
❯ yarn build
[vite:dts] File not found: /Users/lucasduarte/vxdk/src/modules/ui/icons/play.svg.tsx
file: src/modules/ui/icons/play.svg.tsx
error during build:
Error: File not found: /Users/lucasduarte/vxdk/src/modules/ui/icons/play.svg.tsx
    at DirectoryCoordinator.addSourceFileAtPath (/Users/lucasduarte/vxdk/node_modules/ts-morph/dist/ts-morph.js:18641:19)
    at Project.addSourceFileAtPath (/Users/lucasduarte/vxdk/node_modules/ts-morph/dist/ts-morph.js:20086:51)
    at Object.transform (/Users/lucasduarte/vxdk/node_modules/vite-plugin-dts/dist/index.js:141493:17)
    at /Users/lucasduarte/vxdk/node_modules/rollup/dist/shared/rollup.js:22681:25
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Original filename is `play.svg`, but build looking for `play.svg.tsx`

Is the same behavior with options or without options on `solidSvg`
My config:
![image](https://user-images.githubusercontent.com/22087517/146425775-3f628a93-7968-464f-82d1-968157aef2e4.png)

**Comment by jfgodoy** [comment]
hi @lucasdu4rte, thank you for the report. The plugin creates a virtual file with extension ".svg.tsx" to make vite uses the solid compiler for the svg component that this library provides.
I haven't do so much ssr, but I have a minimal ssr project inside `examples/ssr` folder that works.

I don't know how to reproduce your issue, could you provide a minimal project example to further investigate the problem.

**Comment by lucasdu4rte** [comment]
@jfgodoy I solved this with this config `solidSvg({ defaultExport: 'url' })`
